### ISSUE TITLE
Incorrect domain concatenation causes authentication failure (la5.fusionsolar.huawei.com.fusionsolar.huawei.com)

### ISSUE THREAD

**Issue by bgm2002** [JortvanSchijndel/FusionSolarPlus#16]
## System Information

version | core-2025.7.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
container_arch | amd64
user | root
virtualenv | false
python_version | 3.13.3
os_name | Linux
os_version | 6.12.35-haos
arch | x86_64
timezone | America/Santiago
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 4981
Installed Version | 2.0.5
Stage | running
Available Repositories | 2108
Downloaded Repositories | 4

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 16.0
-- | --
update_channel | stable
supervisor_version | supervisor-2025.07.1
agent_version | 1.7.2
docker_version | 28.3.0
disk_total | 30.8 GB
disk_used | 6.3 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | oracle
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Matter Server (8.0.0), Terminal & SSH (9.18.0), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 0
views | 2
mode | storage

</details>

<details><summary>Network Configuration</summary>

adapters | lo (disabled), enp0s3 (enabled, default, auto), hassio (disabled), docker0 (disabled), veth7c4f416 (disabled), vethb7cb29b (disabled), vethaecfab4 (disabled), veth488a3b9 (disabled), vethd025359 (disabled), vethe8f6118 (disabled), vetha24c969 (disabled)
-- | --
ipv4_addresses | lo (127.0.0.1/8), enp0s3 (192.168.100.125/24), hassio (172.30.32.1/23), docker0 (172.30.232.1/23), veth7c4f416 (), vethb7cb29b (), vethaecfab4 (), veth488a3b9 (), vethd025359 (), vethe8f6118 (), vetha24c969 ()
ipv6_addresses | lo (::1/128), enp0s3 (2800:300:6ad2:6360::7/128, 2800:300:6ad2:6360:a8ce:466d:7864:37d7/64, fe80::a2e5:58f7:6bbf:d637/64), hassio (fe80::d892:69ff:fefc:9bd5/64), docker0 (fe80::479:bcff:fee9:55f0/64), veth7c4f416 (fe80::5056:feff:fe0e:458c/64), vethb7cb29b (fe80::e8f0:57ff:fe93:f47f/64), vethaecfab4 (fe80::3095:d1ff:fe50:f7ac/64), veth488a3b9 (fe80::c47f:7cff:fe64:2c1/64), vethd025359 (fe80::8c72:4bff:fe07:c4a8/64), vethe8f6118 (fe80::6c64:f9ff:fe57:7825/64), vetha24c969 (fe80::e8e5:42ff:febd:32ec/64)
announce_addresses | 192.168.100.125, 2800:300:6ad2:6360::7, 2800:300:6ad2:6360:a8ce:466d:7864:37d7, fe80::a2e5:58f7:6bbf:d637

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 16 de julio de 2025, 01:20
-- | --
current_recorder_run | 18 de julio de 2025, 16:13
estimated_db_size | 9.88 MiB
database_engine | sqlite
database_version | 3.48.0

</details>

### Checklist

- [x] I have enabled debug logging for my installation.
- [x] I have filled out the issue template to the best of my ability.
- [x] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [x] This issue is not a duplicate issue of any previous issues.

### Version

V1.5.1

### Devices

Huawei SUN2000-8K-LC0 Inverter  
Software version: V100R023C10SPC108

### Describe the issue

Hi Jort,

First of all, thank you so much for sharing your work and maintaining this integration! It has been very helpful for the community and I truly appreciate the time and effort you put into making FusionSolar data accessible in Home Assistant.

I’m facing an issue with the latest version of FusionSolarPlus where the integration fails to authenticate due to a malformed domain being used for the API call. The integration seems to concatenate the subdomain twice, producing the following hostname:

`la5.fusionsolar.huawei.com.fusionsolar.huawei.com
`

This results in repeated authentication failures, as the domain cannot be resolved.

`FusionSolarPlus: Unexpected error during authentication:
HTTPSConnectionPool(host='la5.fusionsolar.huawei.com.fusionsolar.huawei.com', port=443): Max retries exceeded with url: /unisso/v3/validateUser.action?timeStamp=1752787462938&nonce=c24c39655953ef033cc20347699be926 (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8c31484190>: Failed to resolve 'la5.fusionsolar.huawei.com.fusionsolar.huawei.com' ([Errno -2] Name does not resolve)"))

FusionSolarPlus: Unexpected error during authentication:
Failed to parse: 'la5..fusionsolar.huawei.com', label empty or too long
`

System details:

Home Assistant OS Core 2025.7.2
Supervisor 2025.07.1
Operating System 16.0
Frontend 20250702.2
Platform: Home Assistant OS

Thanks again for your amazing work! Please let me know if you need any additional details or logs to help troubleshoot this.

Apologies if I missed any required information — this is my first time contributing to a public project on GitHub.
I even tried to propose a fix myself, but I was unable to figure it out. :(

### Reproduction steps

1. Install FusionSolarPlus integration from HACS.
2. Attempt to complete authentication using la5 as Subdomain.
3 During setup, enter region la5 (as specified by Huawei’s portal for LATAM, My actual login is: https://la5.fusionsolar.huawei.com/pvmswebsite/login/build/index.html).

Expected behavior:
The integration should normalize the subdomain correctly so that the API calls resolve to:

https://la5.fusionsolar.huawei.com/unisso/v3/validateUser.action

Actual behavior:
The domain is duplicated, leading to:

https://la5.fusionsolar.huawei.com.fusionsolar.huawei.com/unisso/v3/validateUser.action

This breaks the DNS resolution and authentication entirely.

Possible cause:
It seems the issue originates from config_flow.py, around [line 69](https://github.com/JortvanSchijndel/FusionSolarPlus/blob/main/custom_components/fusionsolarplus/config_flow.py#L69), where host_domain and _huawei_subdomain are being combined even if the subdomain already includes the base domain. 

### Debug logs

```text
2025-07-18 16:14:37.119 DEBUG (SyncWorker_6) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Logging into Huawei Fusion Solar API
2025-07-18 16:14:37.836 DEBUG (SyncWorker_6) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Using V3 loging function with encrypted passwords
2025-07-18 16:14:38.166 ERROR (SyncWorker_6) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Retrieved invalid data as login response.
2025-07-18 16:14:38.167 ERROR (SyncWorker_6) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 976, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fusionsolarplus/api/fusion_solar_py/client.py", line 402, in _login
    login_response = r.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 980, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-07-18 16:14:38.183 WARNING (MainThread) [custom_components.fusionsolarplus.config_flow] FusionSolarPlus: Unexpected error during authentication: Failed to process login response
2025-07-18 16:19:01.342 DEBUG (SyncWorker_2) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Logging into Huawei Fusion Solar API
2025-07-18 16:19:01.995 DEBUG (SyncWorker_2) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Using V3 loging function with encrypted passwords
2025-07-18 16:19:02.327 ERROR (SyncWorker_2) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Retrieved invalid data as login response.
2025-07-18 16:19:02.327 ERROR (SyncWorker_2) [custom_components.fusionsolarplus.api.fusion_solar_py.client] Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 976, in json
    return complexjson.loads(self.text, **kwargs)
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
               ~~~~~~~~~~~~~~~^^^
  File "/usr/local/lib/python3.13/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/fusionsolarplus/api/fusion_solar_py/client.py", line 402, in _login
    login_response = r.json()
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 980, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2025-07-18 16:19:02.334 WARNING (MainThread) [custom_components.fusionsolarplus.config_flow] FusionSolarPlus: Unexpected error during authentication: Failed to process login response
```

### Diagnostics dump

The integration cannot be initialized because the domain is malformed during authentication (subdomain is concatenated twice). Therefore, I cannot provide a diagnostics dump since the setup never completes.

**Comment by JortvanSchijndel** [comment]
Hi,

Please make sure you are entering "la5" in the subdomain field and not "la5.fusionsolar.huawei.com". This is a common misconception, that's why I released v1.5.2 which if you enter "la5.fusionsolar.huawei.com" it will automatically strip it down to "la5".
You can download it via HACS by clicking the 3 dots and clicking redownload.
Hopefully this fixes your issue, if not: please reopen the issue.

If you like the integration, please consider to give it a star.
If you have anymore questions, bug reports or feature requests, don't hesitate to open an issue.
Have a nice day! 👋
~Jort

**Comment by bgm2002** [comment]
Hi Jort,

Thank you for the quick reply!

Just to clarify, I am indeed entering only la5 as the subdomain (not the full domain). I also updated to version 1.5.2 and redownloaded it via HACS as suggested, but unfortunately the same error still occurs.

Here is the debug log (after enabling debug logging in configuration.yaml):

2025-07-18 21:34:50 DEBUG (MainThread) [custom_components.fusionsolarplus] Attempting to authenticate...
2025-07-18 21:34:50 ERROR (MainThread) [custom_components.fusionsolarplus.config_flow]
FusionSolarPlus: Unexpected error during authentication:
HTTPSConnectionPool(host='la5.fusionsolar.huawei.com.fusionsolar.huawei.com', port=443): Max retries exceeded with url:
/unisso/v3/validateUser.action?timeStamp=1752787462938&nonce=c24c39655953ef033cc20347699be926
(Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8c31484190>: Failed to resolve
'la5.fusionsolar.huawei.com.fusionsolar.huawei.com' ([Errno -2] Name does not resolve)"))

2025-07-18 21:34:50 ERROR (MainThread) [custom_components.fusionsolarplus.config_flow]
FusionSolarPlus: Unexpected error during authentication:
Failed to parse: 'la5..fusionsolar.huawei.com', label empty or too long

It still tries to connect to:

https://la5.fusionsolar.huawei.com.fusionsolar.huawei.com/unisso/v3/validateUser.action

instead of:

https://la5.fusionsolar.huawei.com/unisso/v3/validateUser.action


---

Possible cause

Looking at the code in custom_components/fusionsolarplus/config_flow.py, the logic around line 69–80 seems to always append .fusionsolar.huawei.com even if it is already present.

Specifically, this section:

if "." in self._huawei_subdomain:
    host_domain = self._huawei_subdomain
else:
    host_domain = f"{self._huawei_subdomain}.fusionsolar.huawei.com"
self._huawei_subdomain = host_domain

If self._huawei_subdomain is already normalized (like la5), it’s fine.
But if some previous step already appended .fusionsolar.huawei.com (or didn’t strip it properly before this block), it ends up duplicating it.

But this is just an idea — I tried to solve it locally and thought I had found the cause, but I wasn’t able fix it myself. :(

Thanks again! I’ve already starred the project. :)

**Comment by bgm2002** [comment]
Hi Jort,

Thank you for the quick reply!

Just to clarify, I am indeed entering only la5 as the subdomain (not the full domain). I also updated to version 1.5.2 and redownloaded it via HACS as suggested, but unfortunately the same error still occurs.

Here is the debug log (after enabling debug logging in configuration.yaml):

2025-07-18 21:34:50 DEBUG (MainThread) [custom_components.fusionsolarplus] Attempting to authenticate...
2025-07-18 21:34:50 ERROR (MainThread) [custom_components.fusionsolarplus.config_flow]
FusionSolarPlus: Unexpected error during authentication:
HTTPSConnectionPool(host='la5.fusionsolar.huawei.com.fusionsolar.huawei.com', port=443): Max retries exceeded with url:
/unisso/v3/validateUser.action?timeStamp=1752787462938&nonce=c24c39655953ef033cc20347699be926
(Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f8c31484190>: Failed to resolve
'la5.fusionsolar.huawei.com.fusionsolar.huawei.com' ([Errno -2] Name does not resolve)"))

2025-07-18 21:34:50 ERROR (MainThread) [custom_components.fusionsolarplus.config_flow]
FusionSolarPlus: Unexpected error during authentication:
Failed to parse: 'la5..fusionsolar.huawei.com', label empty or too long

It still tries to connect to:

https://la5.fusionsolar.huawei.com.fusionsolar.huawei.com/unisso/v3/validateUser.action

instead of:

https://la5.fusionsolar.huawei.com/unisso/v3/validateUser.action

Possible cause

Looking at the code in custom_components/fusionsolarplus/config_flow.py, the logic around line 69–80 seems to always append .fusionsolar.huawei.com even if it is already present.

Specifically, this section:

if "." in self._huawei_subdomain:
host_domain = self._huawei_subdomain
else:
host_domain = f"{self._huawei_subdomain}.fusionsolar.huawei.com"
self._huawei_subdomain = host_domain

If self._huawei_subdomain is already normalized (like la5), it’s fine.
But if some previous step already appended .fusionsolar.huawei.com (or didn’t strip it properly before this block), it ends up duplicating it.

But this is just an idea — I tried to solve it locally and thought I had found the cause, but I wasn’t able fix it myself. :(

Thanks again! I’ve already starred the project. :)

(I've tried to reopen issue, bit github don't let me)

**Comment by JortvanSchijndel** [comment]
Hi,
Thanks for the star!
This is very weird behavior. 

When I add some debug logging I do get a normal url when I enter la5:
```python
[custom_components.fusionsolarplus.api.fusion_solar_py.client] https://la5.fusionsolar.huawei.com/unisso/v3/validateUser.action
```

Also I can't seem to find this section that you are mentioning:

```
if "." in self._huawei_subdomain:
host_domain = self._huawei_subdomain
else:
host_domain = f"{self._huawei_subdomain}.fusionsolar.huawei.com"
self._huawei_subdomain = host_domain
```

Could you please give me a link to the section via Github?

I have added some debugging in the latest commit. I have also added another sanitization part in the client itself. Could you please manually install the custom integration to your Home Assistant installation:
/config/custom_components
Delete the fusionsolarplus folder & restart Home Assistant
download the custom_components/fusionsolarplus folder from github and put it in the /config/custom_components folder
Restart Home Assistant and try to log in.

If it doesn't work please provide me the debug logs.

You are having a really strange issue but I will try my best to help you out!
